// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Cwil63I7oC48JrtsKatDlmrLE2VabWI',
    appId: '1:106421350853:web:48a14059bcac1681bc5bac',
    messagingSenderId: '106421350853',
    projectId: 'foodpal-fd5b6',
    authDomain: 'foodpal-fd5b6.firebaseapp.com',
    storageBucket: 'foodpal-fd5b6.appspot.com',
    measurementId: 'G-VY6XQF8MFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrummcK1Qx_9ImekNnJa8TrgJjAyD62Dw',
    appId: '1:106421350853:android:d5556b8fc8326664bc5bac',
    messagingSenderId: '106421350853',
    projectId: 'foodpal-fd5b6',
    storageBucket: 'foodpal-fd5b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwtyOAypow3EwnSV_D4-kKUeLB9AFYFw0',
    appId: '1:106421350853:ios:206fe05b3aa591f9bc5bac',
    messagingSenderId: '106421350853',
    projectId: 'foodpal-fd5b6',
    storageBucket: 'foodpal-fd5b6.appspot.com',
    iosBundleId: 'com.example.foodpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwtyOAypow3EwnSV_D4-kKUeLB9AFYFw0',
    appId: '1:106421350853:ios:206fe05b3aa591f9bc5bac',
    messagingSenderId: '106421350853',
    projectId: 'foodpal-fd5b6',
    storageBucket: 'foodpal-fd5b6.appspot.com',
    iosBundleId: 'com.example.foodpal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-Cwil63I7oC48JrtsKatDlmrLE2VabWI',
    appId: '1:106421350853:web:2ee080df403a961cbc5bac',
    messagingSenderId: '106421350853',
    projectId: 'foodpal-fd5b6',
    authDomain: 'foodpal-fd5b6.firebaseapp.com',
    storageBucket: 'foodpal-fd5b6.appspot.com',
    measurementId: 'G-4TSX9J4WEJ',
  );
}
